name: "Default Workflow"

on: push

jobs:
  call-workflow-ci-java-maven:
    uses: kumabes-org/reusable-workflows-ci-java-maven/.github/workflows/ci.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"
      project-name: "java-maven-springboot-application"
      java-distribution: "zulu"
      java-version: "11"
      maven-version: "3.8.6"
    secrets: inherit

  call-workflow-sonarqube:
    needs:
      - call-workflow-ci-java-maven
    uses: kumabes-org/reusable-workflows-sonarqube/.github/workflows/main.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"    
      project-name: "java-maven-springboot-application"
    secrets: inherit

  call-workflow-codeql:
    needs:
      - call-workflow-ci-java-maven
    uses: kumabes-org/reusable-workflows-codeql/.github/workflows/main.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"    
      project-name: "java-maven-springboot-application"
      languages: "java"
    secrets: inherit
